# Generated by Django 5.1.3 on 2025-02-04 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=100, null=True)),
                ('PassWord', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductId', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductType', models.CharField(blank=True, max_length=100, null=True)),
                ('Manufacturedate', models.DateField(blank=True, null=True)),
                ('Expirydate', models.CharField(blank=True, max_length=100, null=True)),
                ('Uplaodphoto', models.FileField(blank=True, max_length=250, null=True, upload_to='Media')),
                ('Productprice', models.IntegerField(blank=True, null=True)),
                ('QRCodeImage', models.ImageField(blank=True, null=True, upload_to='product_qr_codes/')),
            ],
        ),
        migrations.CreateModel(
            name='ManufactureTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(blank=True, max_length=100, null=True)),
                ('CompanyAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeedBack', models.CharField(blank=True, max_length=250, null=True)),
                ('Rating', models.CharField(blank=True, max_length=250, null=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleApp.usertable')),
            ],
        ),
    ]
